# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IHM/interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 633)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(480, 220, 381, 321))
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 391, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Board = QtWidgets.QGridLayout(self.layoutWidget)
        self.Board.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Board.setContentsMargins(0, 0, 0, 0)
        self.Board.setSpacing(0)
        self.Board.setObjectName("Board")
        self.case22 = QtWidgets.QPushButton(self.layoutWidget)
        self.case22.setMinimumSize(QtCore.QSize(30, 30))
        self.case22.setMaximumSize(QtCore.QSize(70, 70))
        self.case22.setAutoFillBackground(False)
        self.case22.setText("")
        self.case22.setObjectName("case22")
        self.Board.addWidget(self.case22, 2, 2, 1, 1)
        self.case21 = QtWidgets.QPushButton(self.layoutWidget)
        self.case21.setMinimumSize(QtCore.QSize(30, 30))
        self.case21.setMaximumSize(QtCore.QSize(70, 70))
        self.case21.setAutoFillBackground(False)
        self.case21.setText("")
        self.case21.setObjectName("case21")
        self.Board.addWidget(self.case21, 2, 1, 1, 1)
        self.case11 = QtWidgets.QPushButton(self.layoutWidget)
        self.case11.setMinimumSize(QtCore.QSize(30, 30))
        self.case11.setMaximumSize(QtCore.QSize(70, 70))
        self.case11.setAutoFillBackground(False)
        self.case11.setText("")
        self.case11.setObjectName("case11")
        self.Board.addWidget(self.case11, 1, 1, 1, 1)
        self.case14 = QtWidgets.QPushButton(self.layoutWidget)
        self.case14.setMinimumSize(QtCore.QSize(30, 30))
        self.case14.setMaximumSize(QtCore.QSize(70, 70))
        self.case14.setAutoFillBackground(False)
        self.case14.setText("")
        self.case14.setObjectName("case14")
        self.Board.addWidget(self.case14, 1, 4, 1, 1)
        self.case42 = QtWidgets.QPushButton(self.layoutWidget)
        self.case42.setMinimumSize(QtCore.QSize(30, 30))
        self.case42.setMaximumSize(QtCore.QSize(70, 70))
        self.case42.setAutoFillBackground(False)
        self.case42.setText("")
        self.case42.setObjectName("case42")
        self.Board.addWidget(self.case42, 4, 2, 1, 1)
        self.case41 = QtWidgets.QPushButton(self.layoutWidget)
        self.case41.setMinimumSize(QtCore.QSize(30, 30))
        self.case41.setMaximumSize(QtCore.QSize(70, 70))
        self.case41.setAutoFillBackground(False)
        self.case41.setText("")
        self.case41.setObjectName("case41")
        self.Board.addWidget(self.case41, 4, 1, 1, 1)
        self.case32 = QtWidgets.QPushButton(self.layoutWidget)
        self.case32.setMinimumSize(QtCore.QSize(30, 30))
        self.case32.setMaximumSize(QtCore.QSize(70, 70))
        self.case32.setAutoFillBackground(False)
        self.case32.setText("")
        self.case32.setObjectName("case32")
        self.Board.addWidget(self.case32, 3, 2, 1, 1)
        self.case02 = QtWidgets.QPushButton(self.layoutWidget)
        self.case02.setMinimumSize(QtCore.QSize(30, 30))
        self.case02.setMaximumSize(QtCore.QSize(70, 70))
        self.case02.setAutoFillBackground(False)
        self.case02.setText("")
        self.case02.setObjectName("case02")
        self.Board.addWidget(self.case02, 0, 2, 1, 1)
        self.case20 = QtWidgets.QPushButton(self.layoutWidget)
        self.case20.setMinimumSize(QtCore.QSize(30, 30))
        self.case20.setMaximumSize(QtCore.QSize(70, 70))
        self.case20.setAutoFillBackground(False)
        self.case20.setText("")
        self.case20.setObjectName("case20")
        self.Board.addWidget(self.case20, 2, 0, 1, 1)
        self.case44 = QtWidgets.QPushButton(self.layoutWidget)
        self.case44.setMinimumSize(QtCore.QSize(30, 30))
        self.case44.setMaximumSize(QtCore.QSize(70, 70))
        self.case44.setAutoFillBackground(False)
        self.case44.setText("")
        self.case44.setObjectName("case44")
        self.Board.addWidget(self.case44, 4, 4, 1, 1)
        self.case10 = QtWidgets.QPushButton(self.layoutWidget)
        self.case10.setMinimumSize(QtCore.QSize(30, 30))
        self.case10.setMaximumSize(QtCore.QSize(70, 70))
        self.case10.setAutoFillBackground(False)
        self.case10.setText("")
        self.case10.setObjectName("case10")
        self.Board.addWidget(self.case10, 1, 0, 1, 1)
        self.case31 = QtWidgets.QPushButton(self.layoutWidget)
        self.case31.setMinimumSize(QtCore.QSize(30, 30))
        self.case31.setMaximumSize(QtCore.QSize(70, 70))
        self.case31.setAutoFillBackground(False)
        self.case31.setText("")
        self.case31.setObjectName("case31")
        self.Board.addWidget(self.case31, 3, 1, 1, 1)
        self.case33 = QtWidgets.QPushButton(self.layoutWidget)
        self.case33.setMinimumSize(QtCore.QSize(30, 30))
        self.case33.setMaximumSize(QtCore.QSize(70, 70))
        self.case33.setAutoFillBackground(False)
        self.case33.setText("")
        self.case33.setObjectName("case33")
        self.Board.addWidget(self.case33, 3, 3, 1, 1)
        self.case01 = QtWidgets.QPushButton(self.layoutWidget)
        self.case01.setMinimumSize(QtCore.QSize(30, 30))
        self.case01.setMaximumSize(QtCore.QSize(70, 70))
        self.case01.setAutoFillBackground(False)
        self.case01.setText("")
        self.case01.setObjectName("case01")
        self.Board.addWidget(self.case01, 0, 1, 1, 1)
        self.case34 = QtWidgets.QPushButton(self.layoutWidget)
        self.case34.setMinimumSize(QtCore.QSize(30, 30))
        self.case34.setMaximumSize(QtCore.QSize(70, 70))
        self.case34.setAutoFillBackground(False)
        self.case34.setText("")
        self.case34.setObjectName("case34")
        self.Board.addWidget(self.case34, 3, 4, 1, 1)
        self.case12 = QtWidgets.QPushButton(self.layoutWidget)
        self.case12.setMinimumSize(QtCore.QSize(30, 30))
        self.case12.setMaximumSize(QtCore.QSize(70, 70))
        self.case12.setAutoFillBackground(False)
        self.case12.setText("")
        self.case12.setObjectName("case12")
        self.Board.addWidget(self.case12, 1, 2, 1, 1)
        self.case13 = QtWidgets.QPushButton(self.layoutWidget)
        self.case13.setMinimumSize(QtCore.QSize(30, 30))
        self.case13.setMaximumSize(QtCore.QSize(70, 70))
        self.case13.setAutoFillBackground(False)
        self.case13.setText("")
        self.case13.setObjectName("case13")
        self.Board.addWidget(self.case13, 1, 3, 1, 1)
        self.case40 = QtWidgets.QPushButton(self.layoutWidget)
        self.case40.setMinimumSize(QtCore.QSize(30, 30))
        self.case40.setMaximumSize(QtCore.QSize(70, 70))
        self.case40.setAutoFillBackground(False)
        self.case40.setText("")
        self.case40.setObjectName("case40")
        self.Board.addWidget(self.case40, 4, 0, 1, 1)
        self.case23 = QtWidgets.QPushButton(self.layoutWidget)
        self.case23.setMinimumSize(QtCore.QSize(30, 30))
        self.case23.setMaximumSize(QtCore.QSize(70, 70))
        self.case23.setAutoFillBackground(False)
        self.case23.setText("")
        self.case23.setObjectName("case23")
        self.Board.addWidget(self.case23, 2, 3, 1, 1)
        self.case43 = QtWidgets.QPushButton(self.layoutWidget)
        self.case43.setMinimumSize(QtCore.QSize(30, 30))
        self.case43.setMaximumSize(QtCore.QSize(70, 70))
        self.case43.setAutoFillBackground(False)
        self.case43.setText("")
        self.case43.setObjectName("case43")
        self.Board.addWidget(self.case43, 4, 3, 1, 1)
        self.case03 = QtWidgets.QPushButton(self.layoutWidget)
        self.case03.setMinimumSize(QtCore.QSize(30, 30))
        self.case03.setMaximumSize(QtCore.QSize(70, 70))
        self.case03.setAutoFillBackground(False)
        self.case03.setText("")
        self.case03.setObjectName("case03")
        self.Board.addWidget(self.case03, 0, 3, 1, 1)
        self.case00 = QtWidgets.QPushButton(self.layoutWidget)
        self.case00.setMinimumSize(QtCore.QSize(30, 30))
        self.case00.setMaximumSize(QtCore.QSize(70, 70))
        self.case00.setAutoFillBackground(False)
        self.case00.setText("")
        self.case00.setObjectName("case00")
        self.Board.addWidget(self.case00, 0, 0, 1, 1)
        self.case30 = QtWidgets.QPushButton(self.layoutWidget)
        self.case30.setMinimumSize(QtCore.QSize(30, 30))
        self.case30.setMaximumSize(QtCore.QSize(70, 70))
        self.case30.setAutoFillBackground(False)
        self.case30.setText("")
        self.case30.setObjectName("case30")
        self.Board.addWidget(self.case30, 3, 0, 1, 1)
        self.case24 = QtWidgets.QPushButton(self.layoutWidget)
        self.case24.setMinimumSize(QtCore.QSize(30, 30))
        self.case24.setMaximumSize(QtCore.QSize(70, 70))
        self.case24.setAutoFillBackground(False)
        self.case24.setText("")
        self.case24.setObjectName("case24")
        self.Board.addWidget(self.case24, 2, 4, 1, 1)
        self.case04 = QtWidgets.QPushButton(self.layoutWidget)
        self.case04.setMinimumSize(QtCore.QSize(30, 30))
        self.case04.setMaximumSize(QtCore.QSize(70, 70))
        self.case04.setAutoFillBackground(False)
        self.case04.setText("")
        self.case04.setObjectName("case04")
        self.Board.addWidget(self.case04, 0, 4, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(620, 30, 134, 134))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.Joystick = QtWidgets.QGridLayout(self.layoutWidget1)
        self.Joystick.setContentsMargins(0, 0, 0, 0)
        self.Joystick.setObjectName("Joystick")
        self.up = QtWidgets.QPushButton(self.layoutWidget1)
        self.up.setMinimumSize(QtCore.QSize(40, 40))
        self.up.setMaximumSize(QtCore.QSize(40, 40))
        self.up.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IHM/img/arrow_up.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up.setIcon(icon)
        self.up.setObjectName("up")
        self.direction_selector = QtWidgets.QButtonGroup(MainWindow)
        self.direction_selector.setObjectName("direction_selector")
        self.direction_selector.addButton(self.up)
        self.Joystick.addWidget(self.up, 0, 1, 1, 1)
        self.left = QtWidgets.QPushButton(self.layoutWidget1)
        self.left.setMinimumSize(QtCore.QSize(40, 40))
        self.left.setMaximumSize(QtCore.QSize(40, 40))
        self.left.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("IHM/img/arrow_right.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left.setIcon(icon1)
        self.left.setObjectName("left")
        self.direction_selector.addButton(self.left)
        self.Joystick.addWidget(self.left, 1, 0, 1, 1)
        self.right = QtWidgets.QPushButton(self.layoutWidget1)
        self.right.setMinimumSize(QtCore.QSize(40, 40))
        self.right.setMaximumSize(QtCore.QSize(40, 40))
        self.right.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("IHM/img/arrow_left.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right.setIcon(icon2)
        self.right.setObjectName("right")
        self.direction_selector.addButton(self.right)
        self.Joystick.addWidget(self.right, 1, 2, 1, 1)
        self.down = QtWidgets.QPushButton(self.layoutWidget1)
        self.down.setMinimumSize(QtCore.QSize(40, 40))
        self.down.setMaximumSize(QtCore.QSize(40, 40))
        self.down.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("IHM/img/arrow_down.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down.setIcon(icon3)
        self.down.setObjectName("down")
        self.direction_selector.addButton(self.down)
        self.Joystick.addWidget(self.down, 2, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 490, 183, 83))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ActionSelector = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ActionSelector.setContentsMargins(0, 0, 0, 0)
        self.ActionSelector.setObjectName("ActionSelector")
        self.RButton_insert = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.RButton_insert.setObjectName("RButton_insert")
        self.ActionSelector.addWidget(self.RButton_insert)
        self.RButton_turn = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.RButton_turn.setObjectName("RButton_turn")
        self.ActionSelector.addWidget(self.RButton_turn)
        self.RButton_move_turn = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.RButton_move_turn.setObjectName("RButton_move_turn")
        self.ActionSelector.addWidget(self.RButton_move_turn)
        self.pushButton_04d = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_04d.setEnabled(True)
        self.pushButton_04d.setGeometry(QtCore.QRect(70, 410, 20, 20))
        self.pushButton_04d.setText("")
        self.pushButton_04d.setIcon(icon)
        self.pushButton_04d.setObjectName("pushButton_04d")
        self.direction_insert = QtWidgets.QButtonGroup(MainWindow)
        self.direction_insert.setObjectName("direction_insert")
        self.direction_insert.addButton(self.pushButton_04d)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setEnabled(True)
        self.pushButton_14.setGeometry(QtCore.QRect(150, 410, 20, 20))
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setObjectName("pushButton_14")
        self.direction_insert.addButton(self.pushButton_14)
        self.pushButton_42 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_42.setEnabled(True)
        self.pushButton_42.setGeometry(QtCore.QRect(430, 200, 20, 20))
        self.pushButton_42.setText("")
        self.pushButton_42.setIcon(icon1)
        self.pushButton_42.setObjectName("pushButton_42")
        self.direction_insert.addButton(self.pushButton_42)
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setEnabled(True)
        self.pushButton_34.setGeometry(QtCore.QRect(300, 410, 20, 20))
        self.pushButton_34.setText("")
        self.pushButton_34.setIcon(icon)
        self.pushButton_34.setObjectName("pushButton_34")
        self.direction_insert.addButton(self.pushButton_34)
        self.pushButton_44d = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_44d.setEnabled(True)
        self.pushButton_44d.setGeometry(QtCore.QRect(370, 410, 20, 20))
        self.pushButton_44d.setText("")
        self.pushButton_44d.setIcon(icon)
        self.pushButton_44d.setObjectName("pushButton_44d")
        self.direction_insert.addButton(self.pushButton_44d)
        self.pushButton_44r = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_44r.setEnabled(True)
        self.pushButton_44r.setGeometry(QtCore.QRect(430, 360, 20, 20))
        self.pushButton_44r.setText("")
        self.pushButton_44r.setIcon(icon1)
        self.pushButton_44r.setObjectName("pushButton_44r")
        self.direction_insert.addButton(self.pushButton_44r)
        self.pushButton_43 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_43.setEnabled(True)
        self.pushButton_43.setGeometry(QtCore.QRect(430, 280, 20, 20))
        self.pushButton_43.setText("")
        self.pushButton_43.setIcon(icon1)
        self.pushButton_43.setObjectName("pushButton_43")
        self.direction_insert.addButton(self.pushButton_43)
        self.pushButton_41 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_41.setEnabled(True)
        self.pushButton_41.setGeometry(QtCore.QRect(430, 130, 20, 20))
        self.pushButton_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_41.setText("")
        self.pushButton_41.setIcon(icon1)
        self.pushButton_41.setObjectName("pushButton_41")
        self.direction_insert.addButton(self.pushButton_41)
        self.pushButton_40r = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_40r.setEnabled(True)
        self.pushButton_40r.setGeometry(QtCore.QRect(430, 50, 20, 20))
        self.pushButton_40r.setText("")
        self.pushButton_40r.setIcon(icon1)
        self.pushButton_40r.setObjectName("pushButton_40r")
        self.direction_insert.addButton(self.pushButton_40r)
        self.pushButton_00l = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_00l.setEnabled(True)
        self.pushButton_00l.setGeometry(QtCore.QRect(20, 50, 20, 20))
        self.pushButton_00l.setText("")
        self.pushButton_00l.setIcon(icon2)
        self.pushButton_00l.setObjectName("pushButton_00l")
        self.direction_insert.addButton(self.pushButton_00l)
        self.pushButton_01 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_01.setEnabled(True)
        self.pushButton_01.setGeometry(QtCore.QRect(20, 130, 20, 20))
        self.pushButton_01.setText("")
        self.pushButton_01.setIcon(icon2)
        self.pushButton_01.setObjectName("pushButton_01")
        self.direction_insert.addButton(self.pushButton_01)
        self.pushButton_03 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_03.setEnabled(True)
        self.pushButton_03.setGeometry(QtCore.QRect(20, 280, 20, 20))
        self.pushButton_03.setText("")
        self.pushButton_03.setIcon(icon2)
        self.pushButton_03.setObjectName("pushButton_03")
        self.direction_insert.addButton(self.pushButton_03)
        self.pushButton_04l = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_04l.setEnabled(True)
        self.pushButton_04l.setGeometry(QtCore.QRect(20, 350, 20, 20))
        self.pushButton_04l.setText("")
        self.pushButton_04l.setIcon(icon2)
        self.pushButton_04l.setObjectName("pushButton_04l")
        self.direction_insert.addButton(self.pushButton_04l)
        self.pushButton_00u = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_00u.setEnabled(True)
        self.pushButton_00u.setGeometry(QtCore.QRect(70, 0, 20, 20))
        self.pushButton_00u.setAutoFillBackground(False)
        self.pushButton_00u.setText("")
        self.pushButton_00u.setIcon(icon3)
        self.pushButton_00u.setCheckable(False)
        self.pushButton_00u.setAutoDefault(False)
        self.pushButton_00u.setDefault(False)
        self.pushButton_00u.setFlat(False)
        self.pushButton_00u.setObjectName("pushButton_00u")
        self.direction_insert.addButton(self.pushButton_00u)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setGeometry(QtCore.QRect(150, 0, 20, 20))
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.direction_insert.addButton(self.pushButton_10)
        self.pushButton_02 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_02.setEnabled(True)
        self.pushButton_02.setGeometry(QtCore.QRect(20, 200, 20, 20))
        self.pushButton_02.setText("")
        self.pushButton_02.setIcon(icon2)
        self.pushButton_02.setObjectName("pushButton_02")
        self.direction_insert.addButton(self.pushButton_02)
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setEnabled(True)
        self.pushButton_30.setGeometry(QtCore.QRect(300, 0, 20, 20))
        self.pushButton_30.setText("")
        self.pushButton_30.setIcon(icon3)
        self.pushButton_30.setObjectName("pushButton_30")
        self.direction_insert.addButton(self.pushButton_30)
        self.pushButton_40u = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_40u.setEnabled(True)
        self.pushButton_40u.setGeometry(QtCore.QRect(380, 0, 20, 20))
        self.pushButton_40u.setText("")
        self.pushButton_40u.setIcon(icon3)
        self.pushButton_40u.setObjectName("pushButton_40u")
        self.direction_insert.addButton(self.pushButton_40u)
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setEnabled(True)
        self.pushButton_24.setGeometry(QtCore.QRect(230, 410, 20, 20))
        self.pushButton_24.setText("")
        self.pushButton_24.setIcon(icon)
        self.pushButton_24.setObjectName("pushButton_24")
        self.direction_insert.addButton(self.pushButton_24)
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setEnabled(True)
        self.pushButton_20.setGeometry(QtCore.QRect(220, 0, 20, 20))
        self.pushButton_20.setText("")
        self.pushButton_20.setIcon(icon3)
        self.pushButton_20.setObjectName("pushButton_20")
        self.direction_insert.addButton(self.pushButton_20)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RButton_insert.setText(_translate("MainWindow", "inserer pion"))
        self.RButton_turn.setText(_translate("MainWindow", "tourner pion"))
        self.RButton_move_turn.setText(_translate("MainWindow", "bouger et tourner pion"))
