# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(681, 633)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(480, 220, 220, 269))
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 391, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Board = QtWidgets.QGridLayout(self.layoutWidget)
        self.Board.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Board.setContentsMargins(0, 0, 0, 0)
        self.Board.setSpacing(0)
        self.Board.setObjectName("Board")
        self.case13 = QtWidgets.QPushButton(self.layoutWidget)
        self.case13.setMinimumSize(QtCore.QSize(30, 30))
        self.case13.setMaximumSize(QtCore.QSize(70, 70))
        self.case13.setAutoFillBackground(False)
        self.case13.setText("")
        self.case13.setObjectName("case13")
        self.Board.addWidget(self.case13, 1, 3, 1, 1)
        self.case43 = QtWidgets.QPushButton(self.layoutWidget)
        self.case43.setMinimumSize(QtCore.QSize(30, 30))
        self.case43.setMaximumSize(QtCore.QSize(70, 70))
        self.case43.setAutoFillBackground(False)
        self.case43.setText("")
        self.case43.setObjectName("case43")
        self.Board.addWidget(self.case43, 4, 3, 1, 1)
        self.case11 = QtWidgets.QPushButton(self.layoutWidget)
        self.case11.setMinimumSize(QtCore.QSize(30, 30))
        self.case11.setMaximumSize(QtCore.QSize(70, 70))
        self.case11.setAutoFillBackground(False)
        self.case11.setText("")
        self.case11.setObjectName("case11")
        self.Board.addWidget(self.case11, 1, 1, 1, 1)
        self.case00 = QtWidgets.QPushButton(self.layoutWidget)
        self.case00.setMinimumSize(QtCore.QSize(30, 30))
        self.case00.setMaximumSize(QtCore.QSize(70, 70))
        self.case00.setAutoFillBackground(False)
        self.case00.setText("")
        self.case00.setObjectName("case00")
        self.Board.addWidget(self.case00, 0, 0, 1, 1)
        self.case33 = QtWidgets.QPushButton(self.layoutWidget)
        self.case33.setMinimumSize(QtCore.QSize(30, 30))
        self.case33.setMaximumSize(QtCore.QSize(70, 70))
        self.case33.setAutoFillBackground(False)
        self.case33.setText("")
        self.case33.setObjectName("case33")
        self.Board.addWidget(self.case33, 3, 3, 1, 1)
        self.case40 = QtWidgets.QPushButton(self.layoutWidget)
        self.case40.setMinimumSize(QtCore.QSize(30, 30))
        self.case40.setMaximumSize(QtCore.QSize(70, 70))
        self.case40.setAutoFillBackground(False)
        self.case40.setText("")
        self.case40.setObjectName("case40")
        self.Board.addWidget(self.case40, 4, 0, 1, 1)
        self.case04 = QtWidgets.QPushButton(self.layoutWidget)
        self.case04.setMinimumSize(QtCore.QSize(30, 30))
        self.case04.setMaximumSize(QtCore.QSize(70, 70))
        self.case04.setAutoFillBackground(False)
        self.case04.setText("")
        self.case04.setObjectName("case04")
        self.Board.addWidget(self.case04, 0, 4, 1, 1)
        self.case20 = QtWidgets.QPushButton(self.layoutWidget)
        self.case20.setMinimumSize(QtCore.QSize(30, 30))
        self.case20.setMaximumSize(QtCore.QSize(70, 70))
        self.case20.setAutoFillBackground(False)
        self.case20.setText("")
        self.case20.setObjectName("case20")
        self.Board.addWidget(self.case20, 2, 0, 1, 1)
        self.case42 = QtWidgets.QPushButton(self.layoutWidget)
        self.case42.setMinimumSize(QtCore.QSize(30, 30))
        self.case42.setMaximumSize(QtCore.QSize(70, 70))
        self.case42.setAutoFillBackground(False)
        self.case42.setText("")
        self.case42.setObjectName("case42")
        self.Board.addWidget(self.case42, 4, 2, 1, 1)
        self.case31 = QtWidgets.QPushButton(self.layoutWidget)
        self.case31.setMinimumSize(QtCore.QSize(30, 30))
        self.case31.setMaximumSize(QtCore.QSize(70, 70))
        self.case31.setAutoFillBackground(False)
        self.case31.setText("")
        self.case31.setObjectName("case31")
        self.Board.addWidget(self.case31, 3, 1, 1, 1)
        self.case24 = QtWidgets.QPushButton(self.layoutWidget)
        self.case24.setMinimumSize(QtCore.QSize(30, 30))
        self.case24.setMaximumSize(QtCore.QSize(70, 70))
        self.case24.setAutoFillBackground(False)
        self.case24.setText("")
        self.case24.setObjectName("case24")
        self.Board.addWidget(self.case24, 2, 4, 1, 1)
        self.case44 = QtWidgets.QPushButton(self.layoutWidget)
        self.case44.setMinimumSize(QtCore.QSize(30, 30))
        self.case44.setMaximumSize(QtCore.QSize(70, 70))
        self.case44.setAutoFillBackground(False)
        self.case44.setText("")
        self.case44.setObjectName("case44")
        self.Board.addWidget(self.case44, 4, 4, 1, 1)
        self.case22 = QtWidgets.QPushButton(self.layoutWidget)
        self.case22.setMinimumSize(QtCore.QSize(30, 30))
        self.case22.setMaximumSize(QtCore.QSize(70, 70))
        self.case22.setAutoFillBackground(False)
        self.case22.setText("")
        self.case22.setObjectName("case22")
        self.Board.addWidget(self.case22, 2, 2, 1, 1)
        self.case02 = QtWidgets.QPushButton(self.layoutWidget)
        self.case02.setMinimumSize(QtCore.QSize(30, 30))
        self.case02.setMaximumSize(QtCore.QSize(70, 70))
        self.case02.setAutoFillBackground(False)
        self.case02.setText("")
        self.case02.setObjectName("case02")
        self.Board.addWidget(self.case02, 0, 2, 1, 1)
        self.case23 = QtWidgets.QPushButton(self.layoutWidget)
        self.case23.setMinimumSize(QtCore.QSize(30, 30))
        self.case23.setMaximumSize(QtCore.QSize(70, 70))
        self.case23.setAutoFillBackground(False)
        self.case23.setText("")
        self.case23.setObjectName("case23")
        self.Board.addWidget(self.case23, 2, 3, 1, 1)
        self.case32 = QtWidgets.QPushButton(self.layoutWidget)
        self.case32.setMinimumSize(QtCore.QSize(30, 30))
        self.case32.setMaximumSize(QtCore.QSize(70, 70))
        self.case32.setAutoFillBackground(False)
        self.case32.setText("")
        self.case32.setObjectName("case32")
        self.Board.addWidget(self.case32, 3, 2, 1, 1)
        self.case21 = QtWidgets.QPushButton(self.layoutWidget)
        self.case21.setMinimumSize(QtCore.QSize(30, 30))
        self.case21.setMaximumSize(QtCore.QSize(70, 70))
        self.case21.setAutoFillBackground(False)
        self.case21.setText("")
        self.case21.setObjectName("case21")
        self.Board.addWidget(self.case21, 2, 1, 1, 1)
        self.case03 = QtWidgets.QPushButton(self.layoutWidget)
        self.case03.setMinimumSize(QtCore.QSize(30, 30))
        self.case03.setMaximumSize(QtCore.QSize(70, 70))
        self.case03.setAutoFillBackground(False)
        self.case03.setText("")
        self.case03.setObjectName("case03")
        self.Board.addWidget(self.case03, 0, 3, 1, 1)
        self.case14 = QtWidgets.QPushButton(self.layoutWidget)
        self.case14.setMinimumSize(QtCore.QSize(30, 30))
        self.case14.setMaximumSize(QtCore.QSize(70, 70))
        self.case14.setAutoFillBackground(False)
        self.case14.setText("")
        self.case14.setObjectName("case14")
        self.Board.addWidget(self.case14, 1, 4, 1, 1)
        self.case30 = QtWidgets.QPushButton(self.layoutWidget)
        self.case30.setMinimumSize(QtCore.QSize(30, 30))
        self.case30.setMaximumSize(QtCore.QSize(70, 70))
        self.case30.setAutoFillBackground(False)
        self.case30.setText("")
        self.case30.setObjectName("case30")
        self.Board.addWidget(self.case30, 3, 0, 1, 1)
        self.case34 = QtWidgets.QPushButton(self.layoutWidget)
        self.case34.setMinimumSize(QtCore.QSize(30, 30))
        self.case34.setMaximumSize(QtCore.QSize(70, 70))
        self.case34.setAutoFillBackground(False)
        self.case34.setText("")
        self.case34.setObjectName("case34")
        self.Board.addWidget(self.case34, 3, 4, 1, 1)
        self.case12 = QtWidgets.QPushButton(self.layoutWidget)
        self.case12.setMinimumSize(QtCore.QSize(30, 30))
        self.case12.setMaximumSize(QtCore.QSize(70, 70))
        self.case12.setAutoFillBackground(False)
        self.case12.setText("")
        self.case12.setObjectName("case12")
        self.Board.addWidget(self.case12, 1, 2, 1, 1)
        self.case41 = QtWidgets.QPushButton(self.layoutWidget)
        self.case41.setMinimumSize(QtCore.QSize(30, 30))
        self.case41.setMaximumSize(QtCore.QSize(70, 70))
        self.case41.setAutoFillBackground(False)
        self.case41.setText("")
        self.case41.setObjectName("case41")
        self.Board.addWidget(self.case41, 4, 1, 1, 1)
        self.case01 = QtWidgets.QPushButton(self.layoutWidget)
        self.case01.setMinimumSize(QtCore.QSize(30, 30))
        self.case01.setMaximumSize(QtCore.QSize(70, 70))
        self.case01.setAutoFillBackground(False)
        self.case01.setText("")
        self.case01.setObjectName("case01")
        self.Board.addWidget(self.case01, 0, 1, 1, 1)
        self.case10 = QtWidgets.QPushButton(self.layoutWidget)
        self.case10.setMinimumSize(QtCore.QSize(30, 30))
        self.case10.setMaximumSize(QtCore.QSize(70, 70))
        self.case10.setAutoFillBackground(False)
        self.case10.setText("")
        self.case10.setObjectName("case10")
        self.Board.addWidget(self.case10, 1, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(510, 30, 134, 134))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.Joystick = QtWidgets.QGridLayout(self.layoutWidget1)
        self.Joystick.setContentsMargins(0, 0, 0, 0)
        self.Joystick.setObjectName("Joystick")
        self.up = QtWidgets.QPushButton(self.layoutWidget1)
        self.up.setMinimumSize(QtCore.QSize(40, 40))
        self.up.setMaximumSize(QtCore.QSize(40, 40))
        self.up.setText("")
        self.up.setObjectName("up")
        self.Joystick.addWidget(self.up, 0, 1, 1, 1)
        self.left = QtWidgets.QPushButton(self.layoutWidget1)
        self.left.setMinimumSize(QtCore.QSize(40, 40))
        self.left.setMaximumSize(QtCore.QSize(40, 40))
        self.left.setText("")
        self.left.setObjectName("left")
        self.Joystick.addWidget(self.left, 1, 0, 1, 1)
        self.right = QtWidgets.QPushButton(self.layoutWidget1)
        self.right.setMinimumSize(QtCore.QSize(40, 40))
        self.right.setMaximumSize(QtCore.QSize(40, 40))
        self.right.setText("")
        self.right.setObjectName("right")
        self.Joystick.addWidget(self.right, 1, 2, 1, 1)
        self.down = QtWidgets.QPushButton(self.layoutWidget1)
        self.down.setMinimumSize(QtCore.QSize(40, 40))
        self.down.setMaximumSize(QtCore.QSize(40, 40))
        self.down.setText("")
        self.down.setObjectName("down")
        self.Joystick.addWidget(self.down, 2, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 560, 441, 27))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.ActionSelector = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.ActionSelector.setContentsMargins(0, 0, 0, 0)
        self.ActionSelector.setObjectName("ActionSelector")
        self.Button_insert = QtWidgets.QPushButton(self.layoutWidget2)
        self.Button_insert.setObjectName("Button_insert")
        self.ActionSelector.addWidget(self.Button_insert)
        self.Button_turn = QtWidgets.QPushButton(self.layoutWidget2)
        self.Button_turn.setObjectName("Button_turn")
        self.ActionSelector.addWidget(self.Button_turn)
        self.Button_move_turn = QtWidgets.QPushButton(self.layoutWidget2)
        self.Button_move_turn.setObjectName("Button_move_turn")
        self.ActionSelector.addWidget(self.Button_move_turn)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 440, 183, 83))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RButton_insert = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.RButton_insert.setObjectName("RButton_insert")
        self.verticalLayout.addWidget(self.RButton_insert)
        self.RButton_turn = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.RButton_turn.setObjectName("RButton_turn")
        self.verticalLayout.addWidget(self.RButton_turn)
        self.RButton_move_turn = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.RButton_move_turn.setObjectName("RButton_move_turn")
        self.verticalLayout.addWidget(self.RButton_move_turn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 681, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_insert.setText(_translate("MainWindow", "inserer nv pion"))
        self.Button_turn.setText(_translate("MainWindow", "tourner"))
        self.Button_move_turn.setText(_translate("MainWindow", "bouger+tourner"))
        self.RButton_insert.setText(_translate("MainWindow", "inserer pion"))
        self.RButton_turn.setText(_translate("MainWindow", "tourner pion"))
        self.RButton_move_turn.setText(_translate("MainWindow", "bouger et tourner pion"))
